"""Modified Visits - added ip adress

Revision ID: 25a532ab6a86
Revises: d38c3e31dbaf
Create Date: 2024-01-12 11:52:32.309992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a532ab6a86'
down_revision = 'd38c3e31dbaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
