"""Featured Image

Revision ID: 97c76816a6a9
Revises: 
Create Date: 2024-01-04 01:51:36.924819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97c76816a6a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('featured_image', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_news_slug', ['slug'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('featured_image')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
